### ISSUE TITLE
Error when using script to delete key

### ISSUE THREAD

**Issue by Anna-Livia** [openfisca/tutorial#11]
- When using  `python/scripts/openfisca_json_customizer.py` on a situation with an`id`
- when setting the `update_actions` method to : 
```py
def update_actions(json_content):
  id_key = u'_id'
  json_content = delete_key(json_content, id_key)
  print_value(json_content, id_key)
```

There is an error message even though the `id`key is removed
```
Clef _id introuvable.
```

**Comment by maukoquiroga** [comment]
Closing for now as stale, do not hesitate to reopen it in the future.
