### ISSUE TITLE
Modéliser la réforme des AL 2019

### ISSUE THREAD

**Issue by Anna-Livia** [openfisca/tutorial#14]
Relates to openfisca/openfisca-france#888

Dans le cadre du GT non-recours, nous allons modéliser des réformes pour connaître l'impact des propositions du groupe sur des situations types.

**Comment by Anna-Livia** [comment]
- [  ] Récupérer l'excel fait en séance pour avoir un modèle
- [  ]  Ajouter la génération de matplotlib au framework
- [  ] Ecrire la documentation du Framework

**Comment by maukoquiroga** [comment]
Reste à faire :

- [ ] Nettoyer rapidement l'exemple
- [ ] Intégrer le code R
- [ ] Documenter le code R

**Comment by sandcha** [comment]
- [ ] Déplacer les exemples à la racine du tutorial
- [ ] Indiquer les commandes d'exécution du code / contraintes d'environnement dans un README
- [ ] Ajouter un lien vers le rapport du GT
