### ISSUE TITLE
Clarifier la structure du dépôt tutorial

### ISSUE THREAD

**Issue by sandcha** [openfisca/tutorial#22]
Suite aux travaux du GT non recours et à la formation au Sénat, mettre à jour la structure du dépôt tutorial :
- [ ] S'assurer qu'il n'y a pas de fichier non utilisé.
- [ ] Ajouter un CHANGELOG.md
- [ ] Déplacer les `framework` plus haut dans la hiérarchie des fichiers `python/` afin d'en simplifier la découvrabilité
- [ ] Renommer les fichiers `framework` en des noms explicitant ce que font les scripts

**Comment by maukoquiroga** [comment]
Closing as most of it has been dealt with.

Do not hesitate to re-open if need be.
