### ISSUE TITLE
Clarifier vocabulaire

### ISSUE THREAD

**Issue by benjello** [openfisca/tutorial#24]
En explorant les exemples pythons, je vois que des réformes sont présentées sous les termes:
 - `reforme_parametre` 
 - `reforme_variable`

Je voulais juste préciser que les termes canoniques sont réforme paramétrique et réforme structurelle.

**Comment by Anna-Livia** [comment]
@benjello Est-ce que ces termes (réforme paramétrique et réforme structurelle) sont métier ou OpenFisca ?

**Comment by benjello** [comment]
@Anna-Livia : les deux mon général, le [métier déteignant sur openfisca](https://github.com/openfisca/openfisca-france/blob/cb273820523149cffad300ff851c7105f5922ba5/tests/reforms/test_parametric_reform.py)

**Comment by benjello** [comment]
Pour la complétude, il y a aussi des réformes systémiques (plus fort encore que structurelle) que je verrais bien comme un changement de définition des entités pertinentes au sens du système socio-fiscal.

**Comment by maukoquiroga** [comment]
@Anna-Livia Cela ne te dérange pas si je m'assigne cet issue ?

**Comment by benjello** [comment]
Je me suis permis une [PR](https://github.com/openfisca/openfisca-doc/pull/122) reliée.

**Comment by Anna-Livia** [comment]
@benjello  :
la séparation paramétrique /structurelle me semble être une sémantique supplémentaire à introduire à de nouveaux utilisateurs et j'ai du mal à voir la valeur ajoutée

Alors qu'on pourrait parler des réforme en utilisant le binôme paramètre/variable  :
- créer une réforme qui modifie/créé un paramètre 
- créer une réforme qui modifie /créé une variable
- créer une réforme qui modifie/créé des paramètres et des réformes 

Cela n’est pas le cas si nos nouveaux utilisateurs, en France et à l'étranger, sont habitués à utiliser le terme "structurel"  pour parler de modification de règles de calcul. Ce que je n’ai pas pu conclure à partir de la doc ou du code OpenFisca.

Est-ce que quelqu'un a des billes sur le sujet ?

**Comment by benjello** [comment]
@Anna-Livia : je mentionne juste que ce sont les termes métier utilisés génériquement dans le milieu des économistes. Donc je pense que la sémantique que je propose est bien moins nouvelle qu'une sémantique nouvelle qu'apporterait openfisca.
Disons que je pense qu'openfisca devrait essayer de coller à un contexte existant plutôt que le contraire ;-)

**Comment by Anna-Livia** [comment]
@benjello 
Il me semble que "Structural reform" implique des modification d'ampleur.
https://www.ecb.europa.eu/explainers/tell-me/html/what-are-structural_reforms.en.html
Ce qui me semble décorrélé de l'API qui permet de tester des changements d'impact variés.

Pourquoi est-ce important d'avoir des termes séparés pour les `réformes paramétriques` et les `réformes structurelles` ? (c'est une question naive, mais pourquoi est ce qu'on appelle pas cela "réforme" tout simplement ?)

**Comment by benjello** [comment]
@Anna-Livia : parce que c'est ce qui ressemble le plus à ce qui est utiliser en pratique et qu'il me semble que c'est conforme au principe de moindre surprise.

**Comment by Anna-Livia** [comment]
OK, Je change les tutoriels pour refléter la doc.
