### ISSUE TITLE
Publish OpenFisca data to data.gouv.fr ?

### ISSUE THREAD

**Issue by sandcha** [openfisca/tutorial#26]
Relates to openfisca/openfisca-france#888

**Définition of done :** To-do liste actionable pour la publication, ou pas.

**Comment by Anna-Livia** [comment]
- Les situations sont issues du [livret du pouvoir d'achat]()
- elles se trouvent [ici](https://github.com/openfisca/tutorial/tree/master/python/exemples/gt_non_recours/situations)

**Comment by maukoquiroga** [comment]
For now, and beyond the particular uses of OpenFisca by its contributors, it seems there are some main positioning paths (that are not exclusive):

* As a tool for OpenGovernment (and specially for international development)
* As a tool for government-as-a-platform (through the API)
* As a service (offering OpenFisca by itself)
* As a data-driven policy tool (reforms evaluation)

It looks like is in the latter where the publication of aggregated data, test cases and samples could be more appropriate and useful, as it would be the case of the analysis of impact of reforms.

That being said, I'm not sure what would be a condition for generated data to be published and considered as data. Representativeness ? Fit for purpose ?

Thanks for your thoughts @benjello and @pachevalier

**Comment by maukoquiroga** [comment]
@MattiSG dixit ;

> La première fois que j'avais évoqué la possibilité de faire des datasets à partir des paramètres, ça datait de décembre 2014 (auprès d'Emmanuel). J'en avais parlé à nouveau l'an dernier à data.gouv.fr, il n'y avait pas de ressources dispo pour collaborer, mais un début d'intérêt.

**Comment by maukoquiroga** [comment]
To continue the discussion, some clues:

- Parameters
- Variables
- Situations

**Comment by maukoquiroga** [comment]
We'll probably work on this this Friday in the context of Fridaylabs at Etalab

**Comment by benjello** [comment]
Variables are a choice of implementation.
Parameters can be useful but should be organized to be usable. Somehow the legislation explorer with an export button would be better than a dump.
Situations: I do not see the usefulness of sharing them.

**Comment by maukoquiroga** [comment]
> Parameters can be useful but should be organized to be usable

We'll get there soon.

> Situations: I do not see the usefulness of sharing them.

I see a collection of hypothetical data as a good _starting  kit_, not sure anymore about synthetical data though.

**Comment by maukoquiroga** [comment]
So results of the investigation :

- Parameters and variables (see openfisca/openfisca-france#905)
- Hypothetical data on data.gouv.fr
