### ISSUE TITLE
Outillage non technique pour réalisation de réforme

### ISSUE THREAD

**Issue by sandcha** [openfisca/tutorial#27]
Plan de formation listant les éléments identifiés lors de l'outillage d'un usager non technique qui souhaite réaliser une réforme.

**Definition of done :** F.A.Q. en markdown à partir du GoogleDoc.

**Comment by benjello** [comment]
@sandcha : peut-on avoir le lien vers le google doc ?

**Comment by sandcha** [comment]
@benjello Le [voici](https://docs.google.com/document/d/1i4bYx9PHpdMVfYTsd1rbpkbc65Fvqq7nB1H1DBrYuh0/edit?usp=sharing). En l'état, c'est plus une FAQ qu'un plan de formation.
