### ISSUE TITLE
Organize tutorial/examples/stories notebooks

### ISSUE THREAD

**Issue by benjello** [openfisca/tutorial#3]
# Context

J'autorise (et m'autorise donc) l'utilisation du français pour débattre de la question de l'organisation des notebooks. 

Comme vu IRL avec @Anna-Livia @pachevalier @sandcha @guillett et Marion, les notebooks pratiques sont dispersés, mal renseignés et mal maintenus.

Si nous disposons d'une documentation de qualité orienté développeur, notre offre en terme d'exemple pratique éclairant est faible et peu visible car inorganisée.

# Objectif
Il serait utile d'essayer de faire ressortir des principes clairs pour l'organisation des notebooks. Je lance une proposition dans le débat que je vous invite fortement à critiquer et amender car je ne suis pas un expert des bonnes pratiques même si j'ai eu quelques expériences avec les notebooks.

# Analyse

## Tentative de typologie des notebooks
 
Je tente une typologie à compléter affiner.

### Notebook premiers pas généraliste 

Il s'agirait d'un notebook centré sur l'illustration très rapide des concepts abstrait strictement nécessaires orienté développeur ou utilisateur sophistiqué

Exemple: un getting started notebbok basé le TaxBenefitSystem issu du [country-template](https://github.com/openfisca/country-template/tree/master/openfisca_country_template) illustrant les notions de TaxBenefitSystem, Variables, Parametres et les principales méthode de calcul.
 
### Notebook sur les concepts
 
Notebook qui entrent dans les détails pour certaines fonctionnalités à la fois avancées mais très utiles voire incontournables.

Exemples: 
 - [Howto period](https://github.com/openfisca/tutorial/blob/master/how_to_handle_periods.ipynb)
 - [Howto axes](https://github.com/openfisca/tutorial/blob/master/how_to_handle_axes.ipynb)

### Notebook premiers pas orienté utilisateur d'un pays

Un notebook introduisant rapidement les principaux concepts tout en allant jusqu'aux produits avancés sans entrer dans les détails à l'aide du TaxBenfitSystem d'un pays précis. Il s'appuie sur la familiarité même relative de 'utilsiateur avec le système socio-fiscal pour lui faire découvrir le logiciel.

Exemples:
 - Notebook cours PSE Sénégal
 - [Cas-types simples et visusalisations avancées](https://github.com/openfisca/openfisca-web-notebook/blob/benjello-migration/users/benjello/examples_with_waterfall_bareme.ipynb) 
 - [Getting started France](https://github.com/openfisca/tutorial/blob/master/getting_started.ipynb)    
 
### Notebook "story"

Notebook traitant d'un aspect particulier d'un système socio-fiscal donné et l'illustrate à l'aide d'openfisca
Exemples:
 - [Progressivité de l'impôt](https://github.com/openfisca/openfisca-web-notebook/blob/benjello-migration/users/benjello/Progressivit%C3%A9%20de%20l'imp%C3%B4t%20sur%20le%20revenu.ipynb)
 - [Evolution des cotisations sociales](https://github.com/openfisca/openfisca-web-notebook/blob/benjello-migration/users/benjello/Cotisations%20sociales.ipynb)
 - [Gain à l'enfant](https://github.com/openfisca/openfisca-web-notebook/blob/benjello-migration/users/benjello/Quotient%20familial%20et%20prestations%20familiales-correction_new.ipynb)
 - Application de tel ou tel plf
 
## Requête

Bien entendu nombre de ces notebooks sont imparfaits, il faut sûrement les retravailler mais ils donnent une idée de ce que l'on peut faire (et je n'ai pas parlé de [notebooks avec des données](https://github.com/openfisca/openfisca-france-indirect-taxation/blob/api_migration/openfisca_france_indirect_taxation/examples/notebooks/regressivite_taxation_indirecte.ipynb)). Je pense qu'il est possible de mobiliser des utilisateurs "métiers" pour nous aider à les enrichir.

 Je pense qu'il serait utile de: 
 - définir une première vague limitée de notebooks que l'on veut conserver/améliorer/réaliser pour aider à l'adoption d'openfisca par divers utilisateurs.
 - de définir où on les stocke en essayant ni de multiplier les repo ni de surcharger inutilement certains repo. C'est vague donc à préciser.
 - d'assurer leur maintenance c'est à dire de savoir quand ils sont obsolète pour cause d'évolution du code.  
 - de permettre leur exécution dans mybinder

Qu'en pensez-vous ? 

cc @maukoquiroga  @fpagnoux @MattiSG @cbenz

**Comment by pachevalier** [comment]
Tout n'est pas encore clair dans ma tête mais je pense qu'il faut au moins un notebook (comprendre openfisca en 10 minutes), un peu sur le modèle du [10 minutes guide to pandas](https://pandas.pydata.org/pandas-docs/stable/10min.html), qui soit en français sur openfisca-france et qui permette à un utilisateur français de rentrer dans Openfisca. La doc en anglais c'est parfait mais pour les débutants ça constitue souvent une barrière à l'entrée supplémentaire.

L'idée d'avoir des stories sur la France me semble aussi très intéressante.

**Comment by maukoquiroga** [comment]
Pour en réduire un peu le périmètre, je vous propose qu'on définisse une première _shortlist_ de notebooks qui nous aident sur [nos présentations à l'administration](https://trello.com/c/2JnAjTYm/53-pr%C3%A9sentations-%C3%A0-ladministration).

Le travail étant au point d'achèvement pour le Sénat, je vous propose de nous concentrer sur de notebooks pour, spécifiquement :

- DGTrésor
- DBudget
- CdC
- DGFIP
- AN

Qu'en pensez-vous ?

**Comment by benjello** [comment]
@maukoquiroga : je ne sais pas exactement ce que veux dire un notebook pour les différentes administrations car je ne connais pas le besoin précis.

Néanmoins je pense que pour les acteurs cités, c'est la vision d'ensemble qui a le plus de chance de faire mouche: 
 - Vision des effets en chaîne 
 - Et s'ils ne sont intéressés que par une composante (impôt vs cotisations vs prestations) elle a plus de chances d'apparaître quand on les montre toutes.

@pachevalier : pourrais-tu être plus spécifique ? 
Par exemple, en listant les points que tu aimerais trouver dans 10 minutes to openfisca-fr.
Le problème avec openfisca-france c'est que le cas-type d'école est compliqué à initialiser si on veut montrer l'ensemble des calculs. Donc il faudrait se focaliser sur une composante pouvant être déroulé à partir d'un cas très simple. Et là je ne vois que des calcul d'impôts ou de cotisations sociales. Les prestations font intervenir la dimension temporelle de façon particulièrement compliquée.

@Anna-Livia @sandcha votre avis m'intéresse !

**Comment by benjello** [comment]
Bonjour à tous,

Mes réponses un peu négatives aux premières ont un peu tuer la discussions :-(
Cependant je constate que 
 - les notebooks sont obsolètes (ils ne fonctionnent pas)
 - les notebooks sur `openfisca-web-notebooks` ont été corrigés 

Je suis prêt à les remettre sur pied pour un public économiste.
Bien entendu je vais m'appuyer sur les décompositions, waterfall voire même [les petits widgets](https://github.com/cbenz/openfisca-interactive)
qu'a mis sur pied @cbenz 
Mais je veux savoir si vaut le coup que je le fasse ici ou que vous préfériez que je vive ma vie ailleurs.

Par ailleurs, je pense aussi qu'il serait préférable de converger vers une approche unifiée pour les traitements de cas-types etc. Peut-être qu'il faudrait choisir à raconter une histoire bien définie de la façon la plus claire possible.

En voici quelques unes:
  - Les évolutions des cotisations sociales
  - Les évolutions du barèmes de l'IR des dernières années
  - Les évolutions des Allocations familiales et du QF sur les dernières années (gain à l'enfant etc)

Je pense que si l'on a tous en tête une même histoire et que l'on s'efforce de trouver les moyens plus simples et les représentations les plus éclairantes. L'idée n'est pas de partir du code et de dire vous pouvez faire ce que vous voulez mais plutôt de partir d'un sujet dont les gens ont entendu parler
et de montrer pratiquement que l'on peut aller assez loin assez vite.

**Comment by sandcha** [comment]
Merci pour cette proposition d'organisation ! Il y a beaucoup d'éléments entrant en jeu dans ces choix (diversité d'usages, diversité d'usagers, langues...), d'où un peu de difficulté à répondre. 

Assez d'accord avec la typologie proposée avec les écarts suivants : 
* Les notebooks de concepts actuels peuvent être répartis autrement : la manipulation des periods s'impose à tous donc elle peut figurer dans les syntaxes de base, les axes me semblent plutôt concerner les utilisateurs métier
* J'allierais les **notebooks premiers pas orienté utilisateur d'un pays** et les **stories** dans la mesure où ils s'adressent à des personnes qui arriveraient dans OpenFisca par leur connaissance de concepts d'un système socio-fiscal. Ceci pourrait être décliné au fil du temps selon les profils rencontrés.

Côté histoires à raconter, `Les évolutions du barèmes de l'IR des dernières années` me semble l'exemple à utiliser en premier parce que celui demandant le moins de pré-requis métier pour être compris.

**Comment by sandcha** [comment]
La question que je me pose est : quel notebook pour répondre à quelle question de qui ?

1. `démo d'intro` 
C'est la première fois que je regarde ce logiciel. Que fait OpenFisca ?
Si c'est la rencontre de personnes et d'une législation tel qu'on le présente souvent, un notebook traitant d'une story sur un nombre limité de cas types me semblerait intéressant. Avec visualisation simple pour rendre le résultat plus intelligible.
    > Deux cas types, un schéma de progressivité de l'impôt sur la variation de salaire d'un des cas (par exemple). Ce qui correspondrait au [notebook "Cas-types simples et visusalisations avancées"](https://github.com/openfisca/openfisca-web-notebook/blob/cc27618450e649e1d083d5c0f01c75e9e0aa66d8/users/benjello/examples_with_waterfall_bareme.ipynb) orienté story et avec un nombre réduit de cas types. 
 
2. `memento syntaxique` 
Ca y est, je veux ou dois m'exercer à OpenFisca. Comment transcrire mon idée ? 
J'aime beaucoup le format du 10mn guide à la pandas. Il me semble que cela correspondrait à rendre notre documentation actuelle interactive. Comme il s'adresse à des personnes amenées à coder, il me semble qu'on doit a minima l'avoir en anglais et avec le modèle du country-template.
    > **notebook premiers pas généraliste**  + [howto periods](https://github.com/openfisca/tutorial/blob/dea8d8fe13e7708af36d7ebfc3496dfb02485ad4/notebooks/how_to_handle_periods.ipynb)

3. `métier`
Je suis familier avec le métier. Que puis-je faire avec OpenFisca ?
C'est là où je manque de connaissance sur notre capacité à avoir un notebook qui parle à un chercheur  et à une personne de l'administration ou du parlement. C'est là qu'on a peut-être le plus de variété. Simplement, il me semble que ce doit être sur un modèle réel de pays, dans la langue du pays et que les réformes sont une fonction importante.
    > **notebook sur une story avancée** + [howto axes](https://github.com/openfisca/tutorial/blob/dea8d8fe13e7708af36d7ebfc3496dfb02485ad4/notebooks/how_to_handle_axes.ipynb) + howto reform

**Comment by benjello** [comment]
@sandcha : Ou ije me retrouve sur le 2 qui décortique les étapes. J'ai un exemple de notebook qui contient les différentes étapes que j'ai utilisé en cours avec le [modèle sénégalais](https://github.com/benjello/ppd-micro-simulations-and-public-policies/blob/master/notebooks/Senegal-student-2.ipynb)

**Comment by sandcha** [comment]
@adrienpacifico L'essentiel de la discussion sur l'avenir des tutoriels est ici.

Selon ma compréhension, à ce stade, il y a un accord sur le fait :
* que la mise à jour des notebooks n'est pas opérationnelle et c'est en cours de résolution via #37 
* le contenu des notebooks n'est pas adapté à un nouvel usager openfisca
* qu'il manque un `mémento syntaxique`

@adrienpacifico Es-tu d'accord avec ce bilan ?

**Comment by adrienpacifico** [comment]
@sandcha 

* > que la mise à jour des notebooks n'est pas opérationnelle et c'est en cours de résolution via #37

Oui, mais je pense que c'est **absolument** conditionnel à avoir **les notebooks en place qui tournent correctement** (J'entends avant de vous lancer dans des PR sur le master pour mettre un processus d'intégration continu avec commit automatique complexe).

Pour cela je suis prêt à bosser un peu, mais l'inertie est je pense le plus gros frein à cet objectif.

* >le contenu des notebooks n'est pas adapté à un nouvel usager openfisca

Les choses peuvent être améliorées, mais mon objectif quand j'ai créé les 3 notebooks disponible sur ce repo ( @cbenz et @edarin on remanié les choses) était vraiment de donner les clefs à un débutant pour commencer à utiliser OF. 

Il y a évidemment beaucoup de manques, et je veux bien discuter de qu'il faut pour un nouvel usagé openfisca.

* > qu'il manque un mémento syntaxique

Je ne vois pas exactement ce que c'est. Mon avis est qu'un bon tutoriel, présentant les bonnes pratiques pour lancer les simulations répondrait en partie à ce besoin. 



Après il faut être clair sur vos objectifs à contribuer sur ces tutoriels...

Si un objectif est d'aider des économistes et des citoyens à s'approprier l'outil pour faire des simulations pour comprendre fonctionne le système socio-fiscal, je suis persuadé que c'est la route à suivre.

Quand je vois comment j'ai du tâtonner pour faire mon notebook [comment fonctionne l'impôt sur le revenu](https://github.com/adrienpacifico/openfisca-france-notebook-story), essentiellement car il n'y a pas de **ressources** disponible permettant de lancer des simulations correctement avec OF, je pense que pour quelqu'un extérieur au projet c'est quasi-impossible d'arriver à quelque chose.

Je pense qu'il est possible de faire quelque chose qui permettrait à quelqu'un de faire des choses intéressantes en moins d'un quart d'heure. Si c'était le cas, peu-être qu'il y aurait plein de journalistes, économistes, voire politiques qui publierait des simulations avec OpenFisca lors de différentes réforme et débat public. 

Pour l'instant il n'en est rien, et je trouve cela bien dommage :-) .

**Comment by maukoquiroga** [comment]
Hey @benjello, could we consider this issue dealt with? Otherwise, what would it take thereof?

**Comment by benjello** [comment]
I don't think so and nobody seems to be interested so we should let close at this point.

**Comment by sandcha** [comment]
Closing also because the situation has changed since this discussion (we have up to date notebooks, a rebuilt waterfall and this discussion is in french while it might be interesting to see this in english).
But I'm still willing to help/interested as, imho, we lack a clear tutorial path for new contributors.
