### ISSUE TITLE
Séparer les dossiers /exemples /python de notebooks

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/tutorial#39]
Il existe des dossiers qui contiennent des fichiers `.py`. Je ne sais pas trop à quoi ils correspondent...
 Ne devrait-on pas séparer `openfisca/notebooks-tutorial` de `openfisca/scripts-tutorial` ?

J'ai l'impression que ces deux types distincts d'éléments correspondent à des ensembles disjoints en terme de contributeurs et d'utilisateurs. Je me trompe ?

**Comment by adrienpacifico** [comment]
Personne ? 
@sandcha @maukoquiroga @fpagnoux 

Je suppose qu'il y a un enjeu dispersion de pleins de sous repo vs. un repo à une cohérence interne dans son contenu. Est-ce qu'on continue sur ce repo là ? Est-ce que je forke en créant un repo perso `tutorial-notebooks` ?

**Comment by sandcha** [comment]
Les fichiers python correspondent essentiellement à deux choses :
* des fichiers de la formation [ma première réforme en 4 étapes](https://github.com/openfisca/tutorial/tree/master/python#tutoriels-python). 
Cible : administrateurs de commission des finances
* le code source d'une [analyse pour le Groupe de Travail](https://github.com/openfisca/tutorial/tree/47e276516a156017f3396c8ea3220ce86fca5695/exemples/gt_non_recours#01-032018---supports-du-groupe-de-travail-de-lutte-contre-le-non-recours) de lutte contre le non recours aux aides sociales. Ce code a servi d'[exemple](https://blog.beta.gouv.fr/dinsic/2018/09/24/simuler-impact-loi/) d'utilisation d'openfisca sur un cas réel.

**Comment by fpagnoux** [comment]
Je connais très mal ce repo, donc je ne peux pas aider, mais je peux partager l'impression de @adrienpacifico qu'il semble y avoir des choses qui n'ont pas forcément à voir les unes avec les autres 🙂

**Comment by adrienpacifico** [comment]
Je pense que c'est difficilement utilisable pour l'instant tel quel. 

* Goupe de travail non recours: 
Je ne pense pas que ce soit un tutoriel. C'est un évènement spécifique, il faudrait peut être le migrer vers un repo `openfisca-envents`

* Ma première réforme en 4 étapes:
Je pense que ça peut être un très bon point de départ pour rajouter un notebook `how_to_make_a_reform`, je pense qu'il y en a besoin...


Question : Il y a combien d'administrateurs de la commission des finances utilisent openfisca ?

**Comment by sandcha** [comment]
Ok. Je comprends donc que la structure du dépôt et sa documentation actuelle (type [README](https://github.com/openfisca/tutorial/tree/47e276516a156017f3396c8ea3220ce86fca5695#openfisca-tutorial) principal) ne sont pas claires. 

> Est-ce qu'on continue sur ce repo là ? Est-ce que je forke en créant un repo perso `tutorial-notebooks` ?

S'il s'agit toujours de notebooks servant de tutoriels, je serais pour continuer ici.

> GT) C'est un évènement spécifique, il faudrait peut être le migrer vers un repo `openfisca-envents`

Il semble qu'on ait un [openfisca-web-notebook](https://github.com/openfisca/openfisca-web-notebook) qui contient aujourd'hui des notebooks créés lors d'évènements. D'où la proposition suivante :

* renommer le dépôt `openfisca-web-notebook` en `openfisca-events` 
avec le [contenu actuel](https://github.com/openfisca/openfisca-web-notebook) + le python du Groupe de Travail
* et conserver ce dépôt `tutorial` 
avec `Ma première réforme en 4 étapes` + les notebooks `getting_started`, `how_to_make_a_reform`, ...

@adrienpacifico @fpagnoux Qu'en pensez-vous ? J'ai conscience que ça diffère de l'idée de départ. ^^'

**Comment by sandcha** [comment]
> Question : Il y a combien d'administrateurs de la commission des finances utilisent openfisca ?

Sauf erreur de ma part, les personnes formées (~5 personnes) n'utilisent pas encore openfisca dans leur travail quotidien. Il s'agissait plutôt de formations de sensibilisation/démarrage.

**Comment by benjello** [comment]
Cela me va  @sandcha @adrienpacifico !

**Comment by maukoquiroga** [comment]
Il reste mettre à jour le blog de beta.gouv.fr, on supprime et on ferme non @sandcha ?
