### ISSUE TITLE
Contributor guidelines pour les notebooks.

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/tutorial#43]
Bonjour quelques propositions sur les commits qui concernent les fichiers .ipynb: 

- [x] Les notebooks doivent être exécutés en mode `run_all` avant d'être soumis de sorte que l'`execution count` aille de 1 à N de manière ordonnée.

- [ ] Les modifications qui ne sont pas juste de la mise à niveau (renommage de variable etc), doivent s'assortir d'un lien vers le diff nbdime. [Nbdime](https://github.com/jupyter/nbdime) est une extension Jupyter. Il suffit de l'installer, puis on a un bouton pour générer un diff html. Le dépôt peut être fait sur un gist.

3. ?

**Comment by benjello** [comment]
1. et 2. me vont mais il faudrait:
 - expliquer commetn obtenir le nb-dime et dire où le déposer
 - pouvoir tester le point 1

cc @sandcha @Morendil

**Comment by adrienpacifico** [comment]
Pour #38 , j'ai déposé le nb-dime diff sur gist.

**Comment by maukoquiroga** [comment]
C'est pout-être ça qu'on cherche ? https://nbconvert.readthedocs.io/en/latest/execute_api.html

**Comment by Morendil** [comment]
Le premier point est désormais en place et pour le second il me semble que https://www.reviewnb.com/ fait le job. Je ferme…
