### ISSUE TITLE
Ajouter matplotlib au requirement.txt

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/tutorial#45]

**Comment by adrienpacifico** [comment]
@maukoquiroga peut être un problème de cache, mais le problème de matplotlib n'est toujours pas réglé sur Binder.

**Comment by maukoquiroga** [comment]
@adrienpacifico Oui, c'est dû au problème décrit dans https://github.com/openfisca/tutorial/issues/37#issuecomment-444560844

**Comment by maukoquiroga** [comment]
Bonjour @adrienpacifico, la première fois l'issue a été fermé automatiquement suite au merge de #28, qui introduit `matplotlib` dans le fichier `Pipfile`, l'équivalent de `requirements.txt` mais pour `Pipenv`.

Or, suite à la discussion sur #37, nous découvrons que `binder` n'est pas compatible avec `Pipenv`, donc `Pipfile`.

J'ai fermé maintenant manuellement car il me semble que le problème n'est pas que `matplotlib` ne soit pas inclus, mais que la configuration n'est pas bien faite, la raison pour laquelle j'ai ouvert, hier, #52, pour résoudre le problème.

Or, on peut effectivement attendre à que #52 soit mergée pour considérer cette issue clôturée.

Bonne journée !

**Comment by adrienpacifico** [comment]
Merci @maukoquiroga, j'ai peut-être mal nommé l'issue et j'ai probablement pas été assez descriptif. 
Mais je veux bien fermer l'issue qu'une fois que le binder sur `master` ne plante plus quand on importe matplotlib.

C'est peut être mieux de suggérer à l'ouvreur de l'issue de la fermer pour qu'il puisse vérifier que le problème a bien été réglé ? Ça aurait peut-être permis de voire plus tôt qu'il y avoir un problème `Pipfile`vs `requirements.txt`.
