### ISSUE TITLE
Change reference to baseline

### ISSUE THREAD

**Issue by benjello** [openfisca/tutorial#55]
The disposable income the baseline scenario seems wrong  int the following notebook
https://hub.mybinder.org/user/openfisca-tutorial-ls19f4jp/notebooks/notebooks/getting_started.ipynb

cc @adrienpacifico

**Comment by benjello** [comment]
BTW: use `baseline` instead of `reference`.

**Comment by adrienpacifico** [comment]
@benjello Could you describe what seems wrong. `33979.367` of `revenu_disponible` for `50_000` of `salaire_de_base` doesn't seem that crazy.

**Comment by benjello** [comment]
Ok @adrienpacifico my bad. It is the value out the refom which is surprisingly low.

**Comment by benjello** [comment]
I change the title to address only the other point.

**Comment by adrienpacifico** [comment]
@benjello, I'm not sure why `baseline` should be preferred to `reference`.  Is It  link to English subtleties that I do not master, or is it due to other considerations?

**Comment by benjello** [comment]
Yes it is the appropriate word in english and used throughout `openfisca-core`.

**Comment by benjello** [comment]
Fixed by #56
